image: debian:buster

stages:
  - build

build_energytrace:
  stage: build
  script:
  - apt-get update -qy
  - apt-get install -y build-essential curl gcc-8
  - curl -s https://ess.cs.uos.de/static/.gitlab-ci/MSP430Flasher_1.3.15.tar.xz | tar -C /opt -xJf -
  - gcc-8 -Wall -Wextra -O2 -I/opt/msp430/MSP430Flasher_1.3.15/Source/Inc -L/opt/msp430/MSP430Flasher_1.3.15 -lmsp430 -o energytrace energytrace.c
  - gcc-8 -Wall -Wextra -O2 -I/opt/msp430/MSP430Flasher_1.3.15/Source/Inc -L/opt/msp430/MSP430Flasher_1.3.15 -lmsp430 -o energytracepp energytracepp.c
